### ISSUE TITLE
package version

### ISSUE THREAD

**Issue by eibanez** [arunsrinivasan/cran.stats#1]
Very useful package!

Is is possible to add the package version number to the downloaded data?

Thanks!

**Comment by arunsrinivasan** [comment]
@eibanez thanks. Do you mean to obtain stats and plot them separated by version number? If so it should be possible..

**Comment by eibanez** [comment]
Yes. It would be helpful to have that in the raw data and in the summary/plots.

**Comment by arunsrinivasan** [comment]
Sure. Will try to add this when I work on it next..

**Comment by jangorecki** [comment]
Custom columns to fread from logs was pushed in PR #2
